import os

# ── Database ──────────────────────────────────────────────────────────────────
DB_DIR: str = os.path.join(os.path.dirname(__file__), "data")
PRODUCTS_DB_PATH: str = os.path.join(DB_DIR, "products.db")
CART_DB_PATH: str = os.path.join(DB_DIR, "cart.db")
CHECKPOINTER_DB_PATH: str = os.path.join(DB_DIR, "checkpoints.db")

# ── Database data──────────────────────────────────────────────────────────────


SEED_CATEGORIES = [
    # (category_id, category_description)
    ('Mice & Pointing Devices', 'Computer mice and pointing input devices, covering productivity-grade wireless mice, gaming mice with high-precision sensors, and platform-optimised options for Mac and PC users.'),
    ('Keyboards', 'Mechanical and wireless keyboards for gaming and productivity, including tenkeyless designs, customisable RGB lighting, dedicated macro keys, and low-profile switch options.'),
    ('Monitors & Displays', 'Gaming and professional monitors featuring high refresh rates, QHD and 4K resolutions, curved panels, and IPS/VA display technologies for immersive visual experiences.'),
    ('Headphones & Audio', 'Over-ear headphones, in-ear earbuds, and wireless audio devices with active noise cancellation, premium sound quality, adaptive transparency, and long battery life.'),
    ('Cameras & Drones', 'Mirrorless cameras with full-frame and APS-C sensors for professional photography and video, plus compact consumer drones with intelligent shooting modes and HDR video capability.'),
    ('Wearables & Fitness', 'Smartwatches and fitness trackers offering health monitoring, built-in GPS, heart rate tracking, stress management tools, and seamless integration with iOS and Android ecosystems.'),
    ('Footwear', 'Athletic running shoes, casual boots, and outdoor hiking footwear spanning cushioned road runners, waterproof hiking boots, iconic leather boots, and cosy winter sheepskin styles.'),
    ('Clothing & Apparel', 'Everyday clothing including denim jeans, casual trousers, cotton T-shirts, hoodies, and fleece outerwear from lifestyle and outdoor brands covering a range of fits and styles.'),
    ('Home Appliances', 'Kitchen and household appliances including cordless and robot vacuums, stand mixers, pressure cookers, blenders, smart refrigerators, washing machines, and multi-surface floor cleaners.'),
    ('TVs & Home Entertainment', 'Large-screen televisions featuring 4K HDR, QLED, and OLED display technologies with smart TV platforms, gaming modes, high contrast ratios, and vivid colour reproduction.'),
    ('Gaming Consoles', 'Next-generation and portable gaming consoles delivering high-performance 4K gaming, fast load times, immersive gameplay, and versatile play modes for home and on-the-go gaming.')
]


SEED_PRODUCTS = [
    # (name, description, price, stock, category_id, rating, tags)
   	('Logitech MX Master 3', 'Ergonomic wireless mouse with precision tracking and customizable controls for productivity pros.', 99.99, 150, 1, 4.8, 'wireless,ergonomic,productivity,office,precision,bluetooth,customisable'),
    ('Razer DeathAdder V2', 'High-precision gaming mouse with optical switches and ergonomic grip for competitive play.', 69.99, 120, 1, 4.7, 'gaming,optical,ergonomic,competitive,high-precision'),
    ('Apple Magic Mouse 2', 'Multi-touch wireless mouse with rechargeable battery and sleek design for Mac ecosystems.', 79.99, 90, 1, 4.6, 'wireless,multi-touch,mac,rechargeable,sleek'),
    ('Corsair K95 RGB Platinum', 'Premium mechanical keyboard with customizable RGB and dedicated macro keys for gamers.', 199.99, 60, 2, 4.7, 'mechanical,RGB,gaming,macro,premium'),
    ('Logitech G915 TKL', 'Wireless mechanical keyboard with low-profile GL switches and LIGHTSYNC RGB lighting.', 229.99, 70, 2, 4.6, 'wireless,mechanical,low-profile,RGB,gaming,tenkeyless'),
    ('Razer BlackWidow V3', 'Durable gaming keyboard with tactile switches and dynamic RGB lighting effects.', 139.99, 80, 2, 4.5, 'gaming,mechanical,tactile,RGB,durable'),
    ('Samsung Odyssey G7 27"', 'Curved QHD monitor with 240Hz refresh and deep contrast for immersive gaming.', 699.99, 35, 3, 4.8, 'curved,QHD,240Hz,gaming,immersive'),
    ('LG UltraGear 27GL850', 'QHD IPS gaming monitor with 144Hz refresh rate and rapid response time.', 449.99, 50, 3, 4.7, 'QHD,IPS,144Hz,gaming,fast-response'),
    ('Sony WH-1000XM4', 'Industry-leading noise-cancelling headphones with premium audio clarity and comfort.', 349.99, 40, 4, 4.9, 'noise-cancelling,wireless,premium,over-ear,bluetooth'),
    ('Bose QuietComfort 45', 'Comfortable wireless noise-cancelling headphones with up to 24-hour battery life.', 329.99, 45, 4, 4.8, 'noise-cancelling,wireless,comfort,over-ear,24hr-battery'),
    ('Apple AirPods Pro (2nd Gen)', 'Wireless earbuds with active noise cancellation and adaptive transparency.', 249.99, 65, 4, 4.7, 'wireless,earbuds,noise-cancelling,adaptive-transparency,apple'),
    ('Beats Studio3 Wireless', 'High-performance wireless headphones with pure adaptive noise-cancelling.', 279.99, 55, 4, 4.6, 'wireless,noise-cancelling,over-ear,premium,adaptive'),
    ('Google Pixel Buds Pro', 'Wireless earbuds with premium sound and seamless Google Assistant integration.', 199.99, 70, 4, 4.5, 'wireless,earbuds,google-assistant,premium-sound,android'),
    ('Sony A7 III Mirrorless Camera', 'Full-frame mirrorless camera with excellent low-light performance and advanced autofocus.', 1999.99, 20, 5, 4.8, 'mirrorless,full-frame,low-light,autofocus,professional'),
    ('Canon EOS R6', 'Versatile mirrorless camera with fast continuous shooting and 4K video capture.', 2499.99, 15, 5, 4.7, 'mirrorless,4K,continuous-shooting,professional,video'),
    ('Nikon Z6 II', 'Mirrorless camera offering excellent image quality and dual-processor performance.', 1996.95, 18, 5, 4.7, 'mirrorless,dual-processor,image-quality,professional'),
    ('DJI Mavic Air 2', 'Compact drone with 4K HDR video and intelligent shooting modes.', 799.99, 30, 5, 4.8, 'drone,4K,HDR,compact,intelligent-shooting'),
    ('Fitbit Charge 5', 'Advanced fitness tracker with built-in GPS, stress management, and heart rate monitoring.', 149.95, 120, 6, 4.4, 'fitness-tracker,GPS,heart-rate,stress-management,health'),
    ('Apple Watch Series 9', 'Smartwatch with powerful performance, health tracking, and seamless iPhone integration.', 399.99, 80, 6, 4.8, 'smartwatch,health-tracking,iphone,fitness,apple'),
    ('Samsung Galaxy Watch 6', 'Smartwatch with robust fitness features and long battery life.', 349.99, 75, 6, 4.6, 'smartwatch,fitness,battery-life,android,samsung'),
    ('Nike Air Zoom Pegasus 39', 'Everyday running shoes with responsive cushioning and breathable mesh.', 119.99, 200, 7, 4.6, 'running,cushioning,breathable,everyday,road'),
    ('Adidas Ultraboost 22', 'Boost technology for superior energy return and comfortable long runs.', 179.99, 180, 7, 4.7, 'running,boost,energy-return,comfort,long-distance'),
    ('New Balance Fresh Foam 1080v12', 'Cushioned running shoes with plush Fresh Foam midsole for daily mileage.', 149.99, 160, 7, 4.5, 'running,cushioned,daily-mileage,plush,fresh-foam'),
    ('Saucony Kinvara 13', 'Lightweight road running shoes with springy responsiveness.', 129.99, 140, 7, 4.5, 'running,lightweight,responsive,road,springy'),
    ('Timberland 6-Inch Premium Boot', 'Rugged waterproof boots with padded collar for outdoor durability.', 198.00, 120, 7, 4.5, 'boots,waterproof,rugged,outdoor,padded-collar'),
    ('Dr. Martens 1460', 'Classic leather boots with air-cushioned sole and iconic style.', 150.00, 90, 7, 4.6, 'boots,leather,iconic,air-cushioned,classic'),
    ('Columbia Newton Ridge Plus II', 'Durable waterproof hiking boots with traction-ready outsole.', 129.99, 130, 7, 4.6, 'hiking,waterproof,traction,outdoor,durable'),
    ('UGG Classic Short II', 'Comfortable sheepskin boots with cozy warmth for cold weather.', 159.95, 100, 7, 4.7, 'boots,sheepskin,warm,winter,cozy'),
    ("Levi's 501 Original Jeans", 'Timeless straight-fit denim with button fly and authentic style.', 59.99, 250, 8, 4.4, 'jeans,denim,straight-fit,classic,button-fly'),
    ('Wrangler Authentics Slim Fit', 'Comfortable slim-fit jeans with everyday style and durable build.', 49.99, 200, 8, 4.3, 'jeans,slim-fit,everyday,durable,casual'),
    ("Levi's 511 Slim Fit Jeans", 'Modern slim cut denim with stretch for comfort and mobility.', 69.99, 210, 8, 4.5, 'jeans,slim,stretch,modern,denim'),
    ('Gap Classic Khaki Pants', 'Versatile khaki pants with relaxed fit for everyday wear.', 49.95, 180, 8, 4.2, 'pants,khaki,relaxed,everyday,versatile'),
    ('Uniqlo Men Supima Cotton T-Shirt', 'Soft Supima cotton tee with breathable comfort and classic design.', 14.99, 500, 8, 4.5, 't-shirt,supima-cotton,breathable,classic,soft'),
    ("Hanes Men's Tagless Tee", 'Tagless cotton t-shirt with comfort-first design for daily wear.', 9.99, 400, 8, 4.2, 't-shirt,cotton,tagless,daily,comfort'),
    ('Champion Reverse Weave Hoodie', 'Warm fleece hoodie with classic logo and durable construction.', 59.99, 150, 8, 4.6, 'hoodie,fleece,logo,warm,durable'),
    ('The North Face Denali Fleece Jacket', 'Cozy fleece jacket with reinforced shoulders for outdoor warmth.', 179.00, 80, 8, 4.7, 'jacket,fleece,outdoor,warm,reinforced'),
    ('Patagonia Better Sweater', 'Eco-friendly fleece sweater with full-zip comfort and rugged durability.', 139.00, 100, 8, 4.8, 'sweater,fleece,eco-friendly,full-zip,outdoor'),
    ('Dyson V15 Detect', 'Cordless vacuum with laser dust detection and powerful suction for deep cleaning.', 699.99, 30, 9, 4.8, 'vacuum,cordless,laser-detection,powerful,deep-clean'),
    ('iRobot Roomba i7+', 'Smart robot vacuum with automatic dirt disposal and smart mapping.', 799.99, 25, 9, 4.7, 'robot-vacuum,smart-mapping,auto-disposal,wifi,smart'),
    ('Ninja Foodi Blender', 'High-speed blender with precision blades for smooth blending and crushing ice.', 129.99, 60, 9, 4.6, 'blender,high-speed,ice-crushing,kitchen,smoothie'),
    ('KitchenAid Artisan Mixer', 'Iconic stand mixer with 10 speeds and versatile attachments for baking.', 379.99, 40, 9, 4.9, 'stand-mixer,baking,10-speed,attachments,kitchen'),
    ('Instant Pot Duo 7-in-1', 'Multi-use pressure cooker with customizable programs and reliable performance.', 99.95, 70, 9, 4.7, 'pressure-cooker,multi-use,programmable,kitchen,rice-cooker'),
    ('Samsung Family Hub Refrigerator', 'Smart refrigerator with touchscreen display and flexible storage options.', 2499.99, 10, 9, 4.6, 'refrigerator,smart,touchscreen,storage,connected'),
    ('LG ThinQ Washer', 'Smart washer with AI fabric care and energy-efficient performance.', 899.99, 15, 9, 4.5, 'washer,smart,AI-fabric-care,energy-efficient,laundry'),
    ('Sony X900H 65" TV', '4K HDR Smart LED TV with immersive picture quality and gaming mode.', 1299.99, 20, 10, 4.7, '4K,HDR,smart-TV,LED,gaming-mode,65-inch'),
    ('Samsung Q80T 55" QLED', 'Vibrant QLED display with impressive contrast and motion handling.', 1099.99, 18, 10, 4.6, 'QLED,4K,contrast,motion-handling,55-inch'),
    ('LG CX 65" OLED', 'Stunning OLED picture with deep blacks and rich colors.', 2499.99, 12, 10, 4.8, 'OLED,4K,deep-blacks,rich-colors,65-inch,premium'),
    ('Bissell CrossWave Floor Cleaner', 'All-in-one wet and dry floor cleaner with multi-surface cleaning.', 299.99, 30, 9, 4.5, 'floor-cleaner,wet-dry,multi-surface,all-in-one,vacuum'),
    ('Miele Classic C1 Vacuum', 'Reliable canister vacuum with powerful suction and quiet operation.', 399.99, 25, 9, 4.7, 'vacuum,canister,powerful,quiet,reliable'),
    ('Sony PlayStation 5', 'Next-gen gaming console with lightning-fast load times and immersive gaming.', 499.99, 50, 11, 4.9, 'gaming-console,next-gen,fast-loading,immersive,4K'),
    ('Microsoft Xbox Series X', 'Powerful gaming console with 4K gaming and high performance.', 499.99, 45, 11, 4.8, 'gaming-console,4K,high-performance,xbox,next-gen'),
    ('Nintendo Switch OLED', 'Versatile gaming system with vibrant OLED screen and portable play.', 349.99, 60, 11, 4.9, 'gaming-console,portable,OLED,versatile,handheld'),
    ('Logitech G Pro X Superlight 2', 'Ultra-lightweight wireless gaming mouse with HERO 2 sensor and zero-additive PTFE feet.', 159.99, 80, 1, 4.9, 'wireless,gaming,lightweight,ultra-thin,hero-sensor'),
    ('Razer Basilisk V3 Pro', 'Wireless gaming mouse with HyperScroll tilt wheel and 11 programmable buttons.', 159.99, 70, 1, 4.7, 'wireless,gaming,scroll-wheel,programmable,ergonomic'),
    ('SteelSeries Rival 600', 'Dual-sensor gaming mouse with adjustable weight system and split-trigger buttons.', 79.99, 60, 1, 4.6, 'gaming,dual-sensor,adjustable-weight,rgb,competitive'),
    ('Microsoft Arc Mouse', 'Ultra-slim portable folding mouse with Arc Touch scroll and Bluetooth connectivity.', 74.99, 90, 1, 4.3, 'portable,foldable,bluetooth,travel,slim'),
    ('Logitech MX Anywhere 3', 'Compact wireless mouse with MagSpeed scrolling and multi-device support.', 79.99, 100, 1, 4.6, 'wireless,compact,travel,magspeed,multi-device'),
    ('Corsair Dark Core RGB Pro', 'Wireless gaming mouse with slipstream technology and interchangeable side grips.', 89.99, 65, 1, 4.5, 'wireless,gaming,rgb,slipstream,ergonomic'),
    ('HyperX Pulsefire Haste 2', 'Lightweight honeycomb gaming mouse with 26K DPI sensor and low-latency wireless.', 69.99, 75, 1, 4.7, 'gaming,lightweight,honeycomb,wireless,high-dpi'),
    ('Roccat Kone Pro Air', 'Wireless ergonomic gaming mouse with Owl-Eye 19K sensor and Titan optical switches.', 99.99, 55, 1, 4.6, 'wireless,gaming,ergonomic,optical-switch,lightweight'),
    ('Glorious Model O Wireless', 'Ultra-lightweight 69g honeycomb wireless gaming mouse with BAMF sensor.', 79.99, 65, 1, 4.6, 'wireless,gaming,lightweight,honeycomb,bamf-sensor'),
    ('Anker Vertical Ergonomic Mouse', 'Vertical ergonomic wired mouse with 800–1600 DPI and reduced wrist strain design.', 29.99, 200, 1, 4.4, 'ergonomic,vertical,wired,office,wrist-support'),
    ('Logitech G Pro X TKL', 'Tenkeyless gaming keyboard with swappable GX switches and tournament-grade build.', 129.99, 70, 2, 4.7, 'gaming,tenkeyless,swappable-switches,compact,tournament'),
    ('Ducky One 3', 'Premium 100% hot-swap mechanical keyboard with PBT double-shot keycaps and RGB.', 149.99, 50, 2, 4.8, 'mechanical,hot-swap,pbt-keycaps,rgb,premium'),
    ('SteelSeries Apex Pro TKL', 'TKL keyboard with adjustable OmniPoint magnetic switches and OLED smart display.', 199.99, 55, 2, 4.7, 'gaming,adjustable-actuation,oled-display,tenkeyless,omnipoint'),
    ('HHKB Professional Hybrid Type-S', 'Compact 60% Topre electrostatic keyboard with wireless multi-device support.', 299.99, 30, 2, 4.8, 'compact,60-percent,topre,wireless,silent'),
    ('Keychron K2 Pro', 'Compact wireless QMK/VIA mechanical keyboard with hot-swap and aluminum frame.', 89.99, 90, 2, 4.7, 'wireless,mechanical,hot-swap,qmk,compact'),
    ('Anne Pro 2', 'Compact 60% wireless mechanical keyboard with RGB and tap-arrow function layer.', 59.99, 100, 2, 4.5, 'wireless,60-percent,compact,rgb,bluetooth'),
    ('Corsair K70 RGB Pro', 'Full-size wired gaming keyboard with Cherry MX switches and 8K polling rate.', 159.99, 60, 2, 4.6, 'gaming,full-size,cherry-mx,rgb,8k-polling'),
    ('Das Keyboard 4 Professional', 'Full-size wired mechanical keyboard with Cherry MX switches and anodized aluminum.', 169.99, 45, 2, 4.6, 'mechanical,full-size,cherry-mx,professional,aluminum'),
    ('Razer Huntsman V2', 'Full-size optical gaming keyboard with Razer optical switches and sound dampening foam.', 189.99, 55, 2, 4.6, 'gaming,optical,full-size,sound-dampening,fast-actuation'),
    ('GMMK Pro', 'Modular 75% gasket-mount mechanical keyboard with rotary knob and aluminum frame.', 169.99, 40, 2, 4.7, 'mechanical,modular,gasket-mount,75-percent,aluminum'),
    ('ASUS ROG Swift PG279QM', '27-inch QHD IPS gaming monitor with 240Hz refresh rate and G-Sync Ultimate.', 599.99, 30, 3, 4.8, 'QHD,IPS,240Hz,g-sync,27-inch,gaming'),
    ('Dell Alienware AW3423DW', '34-inch QD-OLED ultrawide monitor with 175Hz refresh and infinite contrast.', 1099.99, 20, 3, 4.9, 'QD-OLED,ultrawide,34-inch,175Hz,infinite-contrast'),
    ('BenQ MOBIUZ EX2710Q', '27-inch QHD IPS gaming monitor with 165Hz and HDRi Eye-Care technology.', 399.99, 40, 3, 4.6, 'QHD,IPS,165Hz,eye-care,27-inch'),
    ('MSI MAG274QRF-QD', '27-inch QHD quantum dot gaming monitor with 165Hz and rapid IPS panel.', 379.99, 35, 3, 4.6, 'QHD,quantum-dot,165Hz,rapid-ips,27-inch'),
    ('Acer Predator XB273U', '27-inch QHD IPS gaming monitor with 170Hz and NVIDIA G-Sync Compatible.', 449.99, 30, 3, 4.7, 'QHD,IPS,170Hz,g-sync,27-inch,predator'),
    ('LG 27GP950-B', '27-inch 4K Nano IPS gaming monitor with 160Hz and HDMI 2.1 for consoles.', 699.99, 25, 3, 4.8, '4K,nano-ips,160Hz,hdmi-2.1,27-inch,gaming'),
    ('Samsung Odyssey Neo G9', '49-inch super ultrawide QLED gaming monitor with Mini LED and 240Hz.', 1799.99, 10, 3, 4.7, 'ultrawide,49-inch,mini-led,QLED,240Hz,curved'),
    ('ASUS ProArt PA279CV', '27-inch 4K IPS professional monitor with 100% sRGB and USB-C connectivity.', 449.99, 35, 3, 4.8, '4K,IPS,professional,sRGB,usb-c,27-inch'),
    ('ViewSonic VP3268-4K', '32-inch 4K professional display with factory-calibrated color accuracy and USB-C hub.', 699.99, 20, 3, 4.7, '4K,professional,32-inch,color-accurate,usb-c,design'),
    ('Gigabyte M27Q', '27-inch QHD IPS gaming monitor with 170Hz and KVM switch functionality.', 299.99, 45, 3, 4.6, 'QHD,IPS,170Hz,kvm-switch,27-inch,gaming'),
    ('Sennheiser Momentum 4 Wireless', 'Premium over-ear wireless headphones with 60-hour battery and adaptive noise cancellation.', 349.99, 40, 4, 4.8, 'wireless,noise-cancelling,over-ear,premium,60hr-battery'),
    ('Sony WF-1000XM5', 'Flagship wireless earbuds with industry-leading noise cancellation and LDAC support.', 299.99, 55, 4, 4.9, 'wireless,earbuds,noise-cancelling,ldac,flagship'),
    ('Samsung Galaxy Buds2 Pro', 'Premium wireless earbuds with intelligent ANC and immersive 360 audio.', 199.99, 70, 4, 4.6, 'wireless,earbuds,noise-cancelling,360-audio,samsung'),
    ('Jabra Elite 85t', 'Advanced true wireless earbuds with adjustable ANC and premium sound profile.', 179.99, 60, 4, 4.6, 'wireless,earbuds,adjustable-anc,premium,jabra'),
    ('Bose QuietComfort Earbuds II', 'Flagship wireless earbuds with CustomTune sound calibration and top-tier ANC.', 279.99, 50, 4, 4.8, 'wireless,earbuds,noise-cancelling,customtune,flagship'),
    ('JBL Tour One M2', 'Premium wireless over-ear headphones with adaptive noise cancellation and spatial sound.', 249.99, 45, 4, 4.6, 'wireless,over-ear,noise-cancelling,spatial-audio,jbl'),
    ('Audio-Technica ATH-M50xBT2', 'Wireless version of the legendary studio monitor headphones with 50-hour battery.', 199.99, 55, 4, 4.7, 'wireless,studio,over-ear,monitor,50hr-battery'),
    ('Marshall Major IV', 'On-ear wireless headphones with 80-hour battery and wireless charging.', 99.99, 80, 4, 4.5, 'wireless,on-ear,80hr-battery,wireless-charging,marshall'),
    ('Nothing Ear (2)', 'Transparent-design wireless earbuds with personalized ANC and LHDC 5.0 codec.', 149.99, 65, 4, 4.5, 'wireless,earbuds,transparent-design,anc,lhdc'),
    ('Shure AONIC 50 Gen 2', 'Premium over-ear wireless headphones with adjustable EQ and broadcast-quality mic.', 379.99, 30, 4, 4.7, 'wireless,over-ear,noise-cancelling,premium,broadcast-mic'),
    ('Sony LinkBuds S', 'Ultra-compact wireless earbuds with seamless ANC/ambient sound switching.', 149.99, 75, 4, 4.6, 'wireless,earbuds,compact,noise-cancelling,ambient'),
    ('Technics EAH-AZ80', 'Flagship wireless earbuds with multipoint connection and LDAC hi-res audio.', 299.99, 35, 4, 4.8, 'wireless,earbuds,flagship,ldac,multipoint'),
    ('Jabra Evolve2 85', 'Professional wireless headset with 10-mic ANC technology and busy light.', 449.99, 30, 4, 4.7, 'wireless,professional,noise-cancelling,office,busy-light'),
    ('Bang & Olufsen Beoplay H9', 'Luxury wireless over-ear headphones with adaptive ANC and premium materials.', 499.99, 20, 4, 4.6, 'wireless,luxury,over-ear,adaptive-anc,premium'),
    ('Anker Soundcore Liberty 4', 'Wireless earbuds with spatial audio, LDAC, and 9-hour battery plus charging case.', 99.99, 90, 4, 4.5, 'wireless,earbuds,spatial-audio,ldac,value'),
    ('JBL Tune 770NC', 'Lightweight wireless headphones with adaptive noise cancellation and 70-hour life.', 99.99, 85, 4, 4.4, 'wireless,on-ear,noise-cancelling,lightweight,70hr-battery'),
    ('Sony WH-CH720N', 'Lightweight over-ear noise-cancelling headphones with 35-hour battery and quick charge.', 149.99, 80, 4, 4.6, 'wireless,over-ear,noise-cancelling,lightweight,quick-charge'),
    ('Skullcandy Crusher Evo', 'Wireless over-ear headphones with personal sound and adjustable haptic bass.', 129.99, 70, 4, 4.3, 'wireless,over-ear,bass,haptic,personal-sound'),
    ('Edifier W820NB Plus', 'Affordable hybrid active noise-cancelling headphones with hi-res audio support.', 79.99, 95, 4, 4.4, 'wireless,over-ear,noise-cancelling,value,hi-res'),
    ('Beyerdynamic Lagoon ANC', 'Wireless foldable headphones with hybrid ANC and personalized sound via app.', 199.99, 40, 4, 4.5, 'wireless,over-ear,noise-cancelling,foldable,personalised'),
    ('Sony ZV-E10', 'Interchangeable-lens vlog camera with directional 3-capsule microphone and flip screen.', 649.99, 40, 5, 4.6, 'mirrorless,vlog,aps-c,flip-screen,content-creator'),
    ('Fujifilm X-T5', '40MP APS-C mirrorless camera with five-axis IBIS and classic film simulation modes.', 1699.99, 25, 5, 4.8, 'mirrorless,aps-c,40mp,ibis,film-simulation'),
    ('Canon EOS R50', 'Compact beginner mirrorless camera with 4K video and dual-pixel autofocus II.', 679.99, 35, 5, 4.6, 'mirrorless,beginner,4K,dual-pixel-af,compact'),
    ('Nikon Z30', 'APS-C mirrorless vlog camera with 4K video and no electronic viewfinder for simplicity.', 756.95, 30, 5, 4.5, 'mirrorless,vlog,aps-c,4K,beginner'),
    ('Sony A6700', 'APS-C flagship mirrorless camera with AI-based autofocus and 5-axis IBIS.', 1399.99, 20, 5, 4.8, 'mirrorless,aps-c,ai-autofocus,ibis,flagship'),
    ('Fujifilm X100VI', 'Premium compact fixed-lens camera with 40MP sensor and built-in ND filter.', 1599.99, 15, 5, 4.9, 'compact,fixed-lens,40mp,film-simulation,nd-filter'),
    ('DJI Mini 4 Pro', 'Sub-250g foldable drone with 4K/60fps video and omnidirectional obstacle sensing.', 759.99, 35, 5, 4.9, 'drone,sub-250g,4K,obstacle-avoidance,foldable'),
    ('DJI Air 3', 'Mid-range camera drone with dual main cameras and 46-minute max flight time.', 1099.99, 25, 5, 4.8, 'drone,dual-camera,4K,long-flight,mid-range'),
    ('Autel EVO Lite+', 'Consumer drone with 6K CMOS sensor and adjustable aperture for creative control.', 949.99, 20, 5, 4.5, 'drone,6K,adjustable-aperture,consumer,creative'),
    ('GoPro Hero 12 Black', 'Action camera with 5.3K video, HyperSmooth 6.0 stabilisation, and water resistance.', 399.99, 60, 5, 4.7, 'action-camera,5.3K,waterproof,stabilisation,wearable'),
    ('DJI Osmo Action 4', 'Action camera with 4K/120fps, 10-bit D-Log M, and magnetic quick-release mount.', 329.99, 50, 5, 4.7, 'action-camera,4K,10-bit,magnetic-mount,waterproof'),
    ('Insta360 X4', '360-degree action camera with 8K 360 video and AI-powered editing features.', 499.99, 35, 5, 4.7, 'action-camera,360-degree,8K,ai-editing,waterproof'),
    ('Canon PowerShot G7X Mark III', 'Compact vlog-optimised camera with 4K video and flip-up touchscreen.', 749.99, 30, 5, 4.6, 'compact,vlog,4K,flip-screen,1-inch-sensor'),
    ('Sony RX100 VII', 'Premium 1-inch sensor compact camera with 20fps burst and pop-up viewfinder.', 1299.99, 20, 5, 4.7, 'compact,1-inch-sensor,20fps,premium,viewfinder'),
    ('Panasonic Lumix G100', 'Compact vlog mirrorless camera with 3-mic directional audio and 4K video.', 647.99, 25, 5, 4.4, 'mirrorless,vlog,directional-mic,4K,compact'),
    ('Garmin Forerunner 265', 'GPS running smartwatch with AMOLED display, training load and recovery feedback.', 449.99, 55, 6, 4.8, 'smartwatch,running,gps,amoled,training-load'),
    ('Garmin Fenix 7', 'Premium multisport GPS watch with solar charging, topo maps, and rugged build.', 699.99, 35, 6, 4.8, 'smartwatch,multisport,gps,solar,rugged,topo-maps'),
    ('Polar Vantage V3', 'Premium sports watch with dual-frequency GPS, ECG, and 140-hour battery life.', 599.99, 30, 6, 4.7, 'smartwatch,sports,dual-gps,ecg,premium,long-battery'),
    ('Withings ScanWatch 2', 'Hybrid smartwatch with medical-grade ECG, SpO2, and 30-day battery life.', 349.99, 40, 6, 4.6, 'hybrid-smartwatch,ecg,spo2,30-day-battery,health'),
    ('Fitbit Sense 2', 'Advanced health smartwatch with continuous EDA scan, ECG, and stress management.', 249.95, 65, 6, 4.5, 'smartwatch,health,ecg,eda,stress-management,fitbit'),
    ('Amazfit GTR 4', 'Affordable smartwatch with dual-band GPS, AMOLED display, and 14-day battery.', 199.99, 80, 6, 4.5, 'smartwatch,dual-gps,amoled,14-day-battery,value'),
    ('Suunto 9 Peak Pro', 'Ultra-thin outdoor sports watch with titanium case, 300-hour GPS battery.', 549.99, 30, 6, 4.7, 'smartwatch,outdoor,titanium,ultra-thin,long-gps'),
    ('Coros Pace 3', 'Lightweight GPS running watch with dual-frequency GPS and 17-day battery.', 229.99, 50, 6, 4.7, 'smartwatch,running,lightweight,gps,long-battery'),
    ('Garmin Vivoactive 5', 'Fitness smartwatch with AMOLED display, 11-day battery, and 30+ sports modes.', 299.99, 55, 6, 4.7, 'smartwatch,fitness,amoled,11-day-battery,multi-sport'),
    ('Samsung Galaxy Watch FE', 'Affordable Samsung smartwatch with health tracking and Galaxy ecosystem integration.', 199.99, 75, 6, 4.4, 'smartwatch,samsung,health,affordable,galaxy'),
    ('Google Pixel Watch 2', 'Wear OS smartwatch with Fitbit health integration and 24-hour battery life.', 349.99, 55, 6, 4.5, 'smartwatch,wear-os,fitbit,google,health'),
    ('Huawei Watch GT 4', 'Smartwatch with 14-day battery, advanced health tracking, and elegant design.', 249.99, 60, 6, 4.5, 'smartwatch,14-day-battery,health,elegant,huawei'),
    ('Fitbit Inspire 3', 'Slim everyday fitness tracker with stress management score and 10-day battery.', 99.95, 100, 6, 4.4, 'fitness-tracker,slim,stress-management,10-day-battery,fitbit'),
    ('Whoop 4.0', 'Screenless fitness and recovery tracker with strain, recovery, and sleep coaching.', 239.99, 45, 6, 4.5, 'fitness-tracker,recovery,strain,sleep-coaching,screenless'),
    ('Fossil Gen 6', 'Wear OS smartwatch with Snapdragon 4100 chip, rapid charging, and SpO2 sensor.', 249.99, 50, 6, 4.3, 'smartwatch,wear-os,rapid-charge,spo2,fashion'),
    ('Brooks Ghost 15', 'Versatile everyday running shoe with plush DNA Loft v2 cushioning and smooth ride.', 139.99, 170, 7, 4.7, 'running,cushioned,everyday,neutral,versatile'),
    ('ASICS Gel-Nimbus 25', 'Premium cushioned running shoe with FF Blast+ Eco foam and PureGEL technology.', 159.99, 150, 7, 4.7, 'running,premium-cushion,puregel,everyday,neutral'),
    ('Hoka Clifton 9', 'Maximally cushioned daily trainer with lightweight EVA midsole and wide toe box.', 139.99, 160, 7, 4.7, 'running,max-cushion,lightweight,daily,wide-toe-box'),
    ('On Cloud 5', 'Lightweight all-day lifestyle running shoe with CloudTec cushioning pods.', 139.99, 175, 7, 4.6, 'running,lifestyle,cloudtec,lightweight,everyday'),
    ('New Balance 574', 'Classic ENCAP cushioning sneaker with suede and mesh upper for everyday style.', 89.99, 200, 7, 4.6, 'sneakers,lifestyle,classic,encap,casual'),
    ('Nike Air Force 1 07', 'Iconic low-top leather basketball sneaker with classic perforated toe box styling.', 110.00, 220, 7, 4.7, 'sneakers,classic,leather,lifestyle,iconic'),
    ('Adidas Stan Smith', 'Iconic minimalist leather tennis sneaker with serrated 3-Stripes detailing.', 99.99, 190, 7, 4.6, 'sneakers,classic,leather,tennis,minimalist'),
    ('Converse Chuck Taylor All Star', 'Timeless canvas high-top sneaker with vulcanised rubber sole and ankle patch.', 59.99, 250, 7, 4.5, 'sneakers,canvas,classic,high-top,iconic'),
    ('Vans Old Skool', 'Classic low-top skate shoe with waffle outsole and signature side stripe.', 70.00, 230, 7, 4.6, 'skate,canvas,suede,classic,side-stripe'),
    ('Merrell Moab 3', 'Waterproof hiking shoe with Vibram TC5+ outsole and M Select DRY membrane.', 139.99, 145, 7, 4.7, 'hiking,waterproof,vibram,trail,durable'),
    ('Salomon X Ultra 4', 'Lightweight waterproof hiking shoe with CONTAGRIP outsole and sensifit chassis.', 149.99, 130, 7, 4.7, 'hiking,waterproof,lightweight,contagrip,trail'),
    ('Keen Targhee III', 'Waterproof mid hiking boot with asymmetrical toe protection and heel-lock lacing.', 154.99, 125, 7, 4.6, 'hiking,waterproof,mid-boot,toe-protection,trail'),
    ('Sorel Caribou', 'Iconic winter boot with removable 9mm felt inner boot and -40°C cold rating.', 169.99, 110, 7, 4.7, 'boots,winter,waterproof,-40c-rated,removable-liner'),
    ('Hunter Original Tall Rain Boot', 'Handcrafted natural rubber Wellington rain boot with adjustable buckle strap.', 165.00, 100, 7, 4.5, 'boots,rain,waterproof,rubber,welly'),
    ('Birkenstock Arizona', 'Classic two-strap sandal with cork-latex footbed and adjustable buckle closure.', 99.99, 180, 7, 4.6, 'sandals,cork,classic,adjustable,comfort'),
    ('Crocs Classic Clog', 'Lightweight EVA clog with Croslite foam cushioning and ventilation port holes.', 44.99, 300, 7, 4.4, 'clogs,lightweight,foam,casual,comfort'),
    ('Clarks Desert Boot', 'Classic suede chukka boot with crepe rubber sole and hand-stitched construction.', 139.99, 115, 7, 4.6, 'boots,suede,chukka,classic,crepe-sole'),
    ('Red Wing Iron Ranger', 'Premium full-grain leather cap-toe boot with Traction Tred outsole.', 329.99, 60, 7, 4.8, 'boots,work,leather,premium,cap-toe'),
    ('Blundstone 500', 'Iconic elastic-sided Chelsea boot with removable shock-absorbing footbed.', 214.95, 130, 7, 4.7, 'boots,chelsea,elastic-sided,waterproof,iconic'),
    ('Nike Air Max 270', 'Lifestyle sneaker with Max Air 270 unit and breathable mesh upper.', 149.99, 185, 7, 4.5, 'sneakers,lifestyle,air-max,breathable,cushioned'),
    ('Brooks Adrenaline GTS 23', 'Stability running shoe with GuideRails support technology and BioMoGo DNA foam.', 134.99, 155, 7, 4.6, 'running,stability,guiderails,everyday,supportive'),
    ('Saucony Ride 16', 'Versatile everyday running shoe with PWRRUN cushioning and vegan-friendly build.', 134.99, 145, 7, 4.6, 'running,everyday,pwrrun,versatile,vegan'),
    ('Mizuno Wave Rider 27', 'Lightweight daily running shoe with ENERZY Foam and signature Wave plate.', 139.99, 140, 7, 4.5, 'running,lightweight,enerzy,wave-plate,daily'),
    ('Altra Lone Peak 7', 'Zero-drop trail running shoe with Trailclaw outsole and FootShape toe box.', 134.99, 120, 7, 4.6, 'trail,zero-drop,wide-toe-box,trail-claw,natural'),
    ('Salomon Speedcross 6', 'Aggressive-lug trail running shoe with wet-terrain grip and quicklace system.', 134.99, 130, 7, 4.7, 'trail,aggressive-lug,wet-grip,quicklace,technical'),
    ("Levi's 550 Relaxed Fit Jeans", 'Relaxed-fit denim jeans with tapered leg and classic five-pocket styling.', 59.99, 220, 8, 4.4, 'jeans,denim,relaxed-fit,tapered,classic'),
    ('Nike Dri-FIT T-Shirt', 'Moisture-wicking athletic tee with Dri-FIT technology for training and workouts.', 30.00, 350, 8, 4.5, 't-shirt,athletic,dri-fit,moisture-wicking,training'),
    ('Adidas Essentials 3-Stripes Hoodie', 'Classic French terry hoodie with iconic 3-Stripes and kangaroo pocket.', 54.99, 250, 8, 4.5, 'hoodie,french-terry,classic,casual,adidas'),
    ('Under Armour Tech 2.0 T-Shirt', 'Smooth performance tee with UA Tech fabric and anti-odour technology.', 24.99, 300, 8, 4.5, 't-shirt,performance,anti-odour,training,moisture-wicking'),
    ("Arc'teryx Atom LT Hoody", 'Lightweight synthetic insulated hoody with Coreloft Compact 60 insulation.', 259.00, 60, 8, 4.8, 'jacket,insulated,lightweight,synthetic,outdoor'),
    ('Patagonia Nano Puff Jacket', 'Packable insulated jacket with PrimaLoft Gold Eco insulation and windproof shell.', 219.00, 75, 8, 4.8, 'jacket,insulated,packable,primaloft,eco-friendly'),
    ('The North Face Thermoball Eco Jacket', 'Lightweight packable jacket with ThermoBall Eco insulation and hand pockets.', 199.00, 80, 8, 4.7, 'jacket,insulated,packable,eco-friendly,lightweight'),
    ('Uniqlo Ultra Light Down Jacket', 'Ultra-packable 90% down jacket that folds into its own pocket for portability.', 69.90, 200, 8, 4.6, 'jacket,down,packable,lightweight,winter'),
    ('Ralph Lauren Classic Fit Oxford Shirt', 'Classic cotton Oxford button-down dress shirt with embroidered Polo player.', 89.50, 130, 8, 4.5, 'shirt,oxford,dress,cotton,classic'),
    ('Tommy Hilfiger Core Flag Polo', 'Classic piqué polo shirt with iconic flag embroidery and ribbed collar.', 59.99, 160, 8, 4.4, 'polo,pique,classic,casual,embroidered'),
    ('Carhartt WIP Chase Sweatshirt', 'Relaxed-fit heavy-brushed cotton sweatshirt with embroidered script logo.', 89.99, 120, 8, 4.6, 'sweatshirt,cotton,relaxed,streetwear,logo'),
    ('Nike Tech Fleece Joggers', 'Tapered jogger pants with Nike Tech Fleece fabric for warmth with low bulk.', 89.99, 180, 8, 4.7, 'joggers,tech-fleece,tapered,athletic,warm'),
    ('Adidas Tiro 21 Training Pants', 'Slim-fit training pants with recycled polyester and side-seam pockets.', 39.99, 200, 8, 4.4, 'training,slim,recycled,athletic,pockets'),
    ('Lululemon ABC Pant', 'Versatile slim-fit trouser with Anti-Ball Crushing fabric for all-day comfort.', 128.00, 90, 8, 4.7, 'pants,versatile,slim,abc,commuter'),
    ('Dickies Original Work Pant', 'Durable cotton-poly blend work pants with stain and wrinkle resistance.', 29.99, 250, 8, 4.4, 'pants,work,durable,stain-resistant,classic'),
    ('Columbia Bora Bora Shorts', 'Quick-dry omni-shade UPF 50 shorts with mesh-lined pockets for outdoor use.', 49.99, 160, 8, 4.4, 'shorts,upf50,quick-dry,outdoor,mesh-lined'),
    ('Patagonia Baggies Shorts', 'Lightweight recycled nylon shorts with DWR finish and mesh brief liner.', 55.00, 150, 8, 4.6, 'shorts,recycled,lightweight,dwr,outdoor'),
    ('Nike Pro Compression Shorts', 'Supportive compression shorts with Dri-FIT fabric and internal brief.', 34.99, 200, 8, 4.5, 'shorts,compression,dri-fit,training,supportive'),
    ('Columbia Silver Ridge Lite Shirt', 'Lightweight omni-shade UPF 40 hiking shirt with vented back and roll-up sleeves.', 59.99, 140, 8, 4.5, 'shirt,upf40,hiking,vented,roll-up-sleeves'),
    ('Icebreaker Merino Wool T-Shirt', 'Natural merino wool base-layer tee with odour resistance and temperature regulation.', 79.99, 120, 8, 4.7, 't-shirt,merino-wool,base-layer,odour-resistant,natural'),
    ('Gildan Heavy Cotton T-Shirt', 'Value heavy-duty 5.3oz cotton t-shirt available in a wide range of colours.', 7.99, 600, 8, 4.2, 't-shirt,cotton,value,heavy-duty,casual'),
    ('Fruit of the Loom Crew Neck Sweatshirt', 'Classic 7.2oz 50/50 blend sweatshirt with set-in sleeves and ribbed cuffs.', 19.99, 400, 8, 4.2, 'sweatshirt,crew-neck,value,classic,casual'),
    ('American Apparel Fine Jersey T-Shirt', 'Soft 4.3oz fine jersey cotton tee with a slim fit and clean finish.', 22.00, 280, 8, 4.4, 't-shirt,fine-jersey,slim-fit,premium-cotton,clean'),
    ('J.Crew Slim-Fit Chino', 'Slim-fit stretch chino pant with stain-repellent finish and classic styling.', 79.50, 170, 8, 4.4, 'pants,chino,slim-fit,stretch,stain-repellent'),
    ('Columbia Watertight II Rain Jacket', 'Packable waterproof rain jacket with Omni-Tech breathable seam-sealed shell.', 79.99, 130, 8, 4.5, 'jacket,waterproof,packable,rain,omni-tech'),
    ('Marmot PreCip Eco Jacket', 'Lightweight packable waterproof rain jacket with NanoPro eco fabric technology.', 99.99, 115, 8, 4.6, 'jacket,waterproof,packable,eco-friendly,lightweight'),
    ("Arc'teryx Beta LT Jacket", 'Hardshell Gore-Tex jacket with waterproofing and 3L construction for alpine use.', 549.00, 40, 8, 4.9, 'jacket,gore-tex,hardshell,waterproof,alpine'),
    ('Fjallraven Greenland Shirt', 'Durable G-1000 Eco canvas shirt-jacket with snap closures and chest pockets.', 140.00, 90, 8, 4.6, 'shirt,canvas,durable,outdoor,snap-closure'),
    ('Banana Republic Aiden Pant', 'Slim-fit traveller trousers with stretch fabric and wrinkle-resistant finish.', 89.99, 140, 8, 4.3, 'pants,slim,travel,wrinkle-resistant,stretch'),
    ('Calvin Klein Modern Cotton Tee', 'Soft modern-fit cotton jersey tee with raised logo waistband and clean neckline.', 29.99, 260, 8, 4.3, 't-shirt,cotton,modern-fit,logo,soft'),
    ('Dyson V8 Animal', 'Cordless vacuum with 40-minute fade-free power and direct-drive cleaner head.', 349.99, 50, 9, 4.7, 'vacuum,cordless,animal,fade-free,40-minute'),
    ('Shark IZ462H Vertex Cordless Vacuum', 'DuoClean PowerFins cordless vacuum with anti-allergen complete seal technology.', 299.99, 45, 9, 4.6, 'vacuum,cordless,duoclean,anti-allergen,powerfins'),
    ('iRobot Roomba j7+', 'Robot vacuum with iRobot OS, obstacle avoidance, and clean base auto-disposal.', 849.99, 25, 9, 4.7, 'robot-vacuum,obstacle-avoidance,smart,auto-disposal,mapping'),
    ('Ecovacs Deebot X2 Omni', 'Robot vacuum and mop combo with hot water self-cleaning and auto-empty base.', 1199.99, 15, 9, 4.6, 'robot-vacuum,mop,self-cleaning,auto-empty,hot-water'),
    ('Roborock S8 Pro Ultra', 'Robot vacuum and mop with sonic mopping, self-wash, and auto-refill dock.', 1599.99, 12, 9, 4.8, 'robot-vacuum,mop,sonic-mopping,self-wash,auto-refill'),
    ('Breville Barista Express', 'All-in-one espresso machine with built-in conical burr grinder and steam wand.', 699.99, 30, 9, 4.8, 'espresso,built-in-grinder,barista,steam-wand,coffee'),
    ("De'Longhi Magnifica Evo", 'Fully automatic espresso machine with LatteCrema system and bean-to-cup brewing.', 799.99, 25, 9, 4.7, 'espresso,automatic,bean-to-cup,latte,cappuccino'),
    ('Nespresso Vertuo Next', 'Capsule coffee machine with centrifusion technology and WiFi connectivity.', 179.99, 70, 9, 4.6, 'coffee,capsule,vertuo,wifi,single-serve'),
    ('Breville Smart Oven Air Fryer Pro', 'Countertop convection oven with 13 cooking functions and Element IQ system.', 449.99, 35, 9, 4.7, 'oven,air-fryer,convection,countertop,multi-function'),
    ('Ninja Foodi Smart XL Grill', 'Indoor grill and air fryer with smart cook system and XL 6-quart capacity.', 329.99, 40, 9, 4.6, 'grill,air-fryer,indoor,smart,xl-capacity'),
    ('COSORI Air Fryer Pro LE', '5-quart digital air fryer with 13 cooking presets and bi-directional air circulation.', 99.99, 80, 9, 4.7, 'air-fryer,digital,5-quart,13-presets,compact'),
    ('Instant Pot Pro Plus', 'Smart Wi-Fi enabled 10-in-1 pressure cooker with app control and sous vide mode.', 149.95, 55, 9, 4.6, 'pressure-cooker,wifi,smart,10-in-1,sous-vide'),
    ('Crock-Pot 7-Quart Slow Cooker', 'Large-capacity programmable slow cooker with locking lid for portability.', 54.99, 100, 9, 4.5, 'slow-cooker,programmable,7-quart,locking-lid,large'),
    ('NutriBullet Pro 900', 'Personal blender with 900-watt motor and colossal cup for smoothies and shakes.', 99.99, 90, 9, 4.6, 'blender,personal,900-watt,smoothie,compact'),
    ('Vitamix A3500', 'Professional-grade self-cleaning blender with touchscreen controls and wireless connectivity.', 649.95, 25, 9, 4.9, 'blender,professional,self-cleaning,touchscreen,wireless'),
    ('Anova Precision Cooker Pro', 'Professional sous vide cooker with Wi-Fi, 1200W heating power and quiet operation.', 199.99, 35, 9, 4.7, 'sous-vide,precision,wifi,1200w,professional'),
    ('Cuisinart 14-Cup Food Processor', 'Large food processor with 720W motor, stainless steel disc and chopping blade.', 199.99, 40, 9, 4.6, 'food-processor,14-cup,720w,stainless,versatile'),
    ('Breville Juice Fountain Plus', 'Centrifugal juicer with 850W motor and extra-wide 3-inch feed chute.', 149.95, 45, 9, 4.5, 'juicer,centrifugal,850w,wide-chute,juice'),
    ('LG InstaView French Door Refrigerator', 'Smart refrigerator with knock-to-see InstaView glass panel and Door-in-Door storage.', 2799.99, 8, 9, 4.6, 'refrigerator,smart,instaview,french-door,door-in-door'),
    ('Samsung Bespoke 4-Door Flex Refrigerator', 'Customisable modular refrigerator with interchangeable colour panels and FlexZone.', 2599.99, 10, 9, 4.7, 'refrigerator,bespoke,modular,4-door,customisable'),
    ('Whirlpool Front Load Washer', 'Front-load washing machine with Load & Go XL dispenser and 5.0 cu ft capacity.', 999.99, 15, 9, 4.5, 'washer,front-load,load-and-go,large-capacity,quiet'),
    ('LG DLGX5501V Gas Dryer', 'Smart gas dryer with TurboSteam, sensor dry, and 7.4 cu ft ultra-large capacity.', 1049.99, 12, 9, 4.6, 'dryer,gas,turboseteam,sensor-dry,large-capacity'),
    ('Bosch 300 Series Dishwasher', 'Ultra-quiet 44 dBA dishwasher with PrecisionWash and flexible third rack.', 799.99, 20, 9, 4.8, 'dishwasher,quiet,precisionwash,third-rack,energy-efficient'),
    ('Shark Navigator Lift-Away', 'Upright lift-away vacuum with anti-allergen seal and 30-foot cord reach.', 199.99, 55, 9, 4.5, 'vacuum,upright,lift-away,anti-allergen,corded'),
    ('Eufy RoboVac G30', 'Robot vacuum with smart dynamic navigation and 2000Pa powerful suction.', 199.99, 50, 9, 4.5, 'robot-vacuum,smart-navigation,2000pa,quiet,mapping'),
    ('Tineco Floor One S5', 'Smart wet-dry vacuum and mop combo with iLoop sensor and self-cleaning mode.', 349.99, 35, 9, 4.6, 'floor-cleaner,wet-dry,smart,self-cleaning,iloop'),
    ('iRobot Braava Jet m6', 'Smart robot mop with precision jet spray and imprint smart mapping technology.', 449.99, 30, 9, 4.5, 'robot-mop,jet-spray,smart-mapping,wifi,precision'),
    ('Cuisinart DGB-900BC Grind & Brew', '12-cup automatic grind-and-brew coffee maker with built-in burr grinder.', 159.99, 50, 9, 4.5, 'coffee-maker,grind-and-brew,burr-grinder,12-cup,automatic'),
    ('Hamilton Beach 12-Cup Coffee Maker', 'Programmable drip coffee maker with brew strength control and keep-warm plate.', 34.99, 150, 9, 4.3, 'coffee-maker,drip,programmable,12-cup,keep-warm'),
    ('Hoover WindTunnel 3 Upright Vacuum', 'Corded upright vacuum with WindTunnel 3 technology and HEPA media filter.', 129.99, 60, 9, 4.4, 'vacuum,upright,hepa,windtunnel,corded'),
    ('Samsung QN90B Neo QLED 65"', '65-inch Neo QLED TV with Mini LED, Quantum Matrix Pro and ultra-viewing angle.', 1799.99, 18, 10, 4.8, 'neo-qled,mini-led,4K,65-inch,quantum-matrix'),
    ('LG A2 55" OLED', 'Entry-level 55-inch OLED TV with self-lit pixels and Dolby Vision/Atmos support.', 799.99, 25, 10, 4.6, 'oled,55-inch,dolby-vision,dolby-atmos,entry-level'),
    ('Sony A80K 65" OLED', '65-inch OLED TV with Cognitive Processor XR and Acoustic Surface Audio+.', 1799.99, 14, 10, 4.8, 'oled,65-inch,cognitive-xr,acoustic-surface,4K'),
    ('TCL 6-Series 55" Mini-LED', '55-inch Mini-LED QLED TV with Dolby Vision IQ and full-array local dimming.', 649.99, 28, 10, 4.7, 'mini-led,qled,55-inch,dolby-vision,local-dimming'),
    ('Hisense U8H 65"', '65-inch Mini-LED ULED TV with 1000-nit brightness and quantum dot colour.', 999.99, 20, 10, 4.7, 'mini-led,uled,65-inch,1000-nit,quantum-dot'),
    ('Vizio P-Series Quantum 65"', '65-inch quantum colour display with ProGaming Engine and Dolby Vision support.', 999.99, 18, 10, 4.5, 'qled,65-inch,quantum-color,gaming,dolby-vision'),
    ('Samsung The Frame 55"', 'Lifestyle 55-inch art TV with matte display, Art Mode and customisable bezels.', 1299.99, 20, 10, 4.6, 'lifestyle,art-mode,matte,55-inch,customisable-bezel'),
    ('LG QNED90 65"', '65-inch QNED Mini LED TV with quantum NanoCell and 120Hz refresh rate.', 1299.99, 16, 10, 4.6, 'qned,mini-led,65-inch,120Hz,nanocell'),
    ('Sony X95K 75"', '75-inch Mini LED TV with full-array local dimming and HDMI 2.1 gaming support.', 2799.99, 8, 10, 4.7, 'mini-led,75-inch,local-dimming,hdmi-2.1,gaming'),
    ('TCL 5-Series 50" QLED', 'Budget-friendly 50-inch QLED TV with Dolby Vision and Google TV smart platform.', 449.99, 32, 10, 4.5, 'qled,50-inch,dolby-vision,google-tv,value'),
    ('Hisense A6H 50"', 'Affordable 50-inch 4K HDR LED TV with DTS Virtual:X and Alexa built-in.', 299.99, 40, 10, 4.3, '4K,50-inch,hdr,alexa,value'),
    ('Philips OLED+937 65"', '65-inch Ambilight OLED TV with Bowers & Wilkins 3.1.2 sound system.', 2999.99, 8, 10, 4.8, 'oled,ambilight,65-inch,bowers-wilkins,premium-audio'),
    ('Panasonic LZ2000 65" OLED', '65-inch HCX Pro AI processor OLED TV with Dolby Atmos and filmmaker mode.', 2499.99, 10, 10, 4.8, 'oled,65-inch,filmmaker-mode,dolby-atmos,hcx-pro'),
    ('LG C3 55" OLED evo', '55-inch OLED evo TV with α9 AI Processor Gen6 and NVIDIA G-Sync compatible.', 1299.99, 22, 10, 4.9, 'oled-evo,55-inch,g-sync,120Hz,gaming'),
    ('Samsung S95C 65" QD-OLED', '65-inch quantum dot OLED TV with Neural Quantum Processor 4K and LaserSlim design.', 2599.99, 10, 10, 4.9, 'qd-oled,65-inch,neural-quantum,laserslim,premium'),
    ('Nintendo Switch Lite', 'Compact dedicated handheld gaming system with integrated controls and vibrant screen.', 199.99, 80, 11, 4.8, 'handheld,portable,compact,nintendo,dedicated'),
    ('Xbox Series S', 'Next-gen digital-only gaming console with 1440p gaming and 512GB SSD.', 299.99, 65, 11, 4.7, 'gaming-console,digital,next-gen,1440p,compact'),
    ('Valve Steam Deck OLED', 'Portable PC gaming handheld with 7.4-inch OLED display and AMD APU processor.', 549.99, 45, 11, 4.9, 'handheld,pc-gaming,oled,portable,steam'),
    ('ASUS ROG Ally', 'Windows 11 gaming handheld with AMD Ryzen Z1 Extreme chip and 1080p display.', 699.99, 40, 11, 4.6, 'handheld,windows,amd,1080p,gaming'),
    ('Lenovo Legion Go', 'Large-screen Windows gaming handheld with detachable controllers and TDP flex mode.', 699.99, 35, 11, 4.5, 'handheld,windows,detachable-controllers,large-screen,gaming'),
    ('Meta Quest 3', 'Mixed-reality standalone VR headset with Snapdragon XR2 Gen 2 and colour passthrough.', 499.99, 50, 11, 4.7, 'vr,standalone,mixed-reality,passthrough,meta'),
    ('PlayStation VR2', 'PS5 VR headset with eye tracking, adaptive triggers and 4K HDR OLED display.', 549.99, 35, 11, 4.6, 'vr,ps5,eye-tracking,oled,haptic'),
    ('NVIDIA Shield TV Pro', 'Streaming media player and Android gaming device with Tegra X1+ processor.', 199.99, 55, 11, 4.7, 'streaming,android-gaming,tegra,4K,plex-server'),
    ('PlayStation Portal', 'Remote-play handheld for PS5 with DualSense haptics and adaptive triggers.', 199.99, 60, 11, 4.3, 'handheld,remote-play,ps5,haptics,adaptive-triggers'),
    ('Logitech G Cloud Gaming Handheld', 'Cloud gaming handheld with 7-inch IPS display and 12-hour battery life.', 349.99, 40, 11, 4.3, 'handheld,cloud-gaming,lightweight,12hr-battery,wifi'),
    ('Xbox Series S 1TB Carbon Black', 'Expanded-storage next-gen digital Xbox Series S with 1TB and carbon black finish.', 349.99, 50, 11, 4.7, 'gaming-console,digital,1tb,next-gen,compact'),
    ('ASUS ROG Ally X', 'Upgraded ROG Ally with larger 80Wh battery, 24GB RAM and improved cooling.', 799.99, 30, 11, 4.7, 'handheld,windows,amd,24gb-ram,long-battery'),
    ('Analogue Pocket', 'FPGA-based handheld gaming system compatible with original Game Boy cartridges.', 219.99, 25, 11, 4.8, 'handheld,retro,fpga,gameboy,classic'),
    ('GPD Win 4', 'Compact gaming handheld PC with AMD Ryzen 7 6800U and slide-out keyboard.', 799.99, 20, 11, 4.5, 'handheld,gaming-pc,ryzen,slide-keyboard,compact'),
    ('Razer Edge 5G', 'Android cloud gaming tablet-handheld with Snapdragon G3x Gen 1 gaming platform.', 399.99, 30, 11, 4.2, 'handheld,android,cloud-gaming,snapdragon,5g'),
    ('Atari VCS 800', 'Modern retro gaming console and PC hybrid running Linux with Atari Vault classics.', 299.99, 20, 11, 3.9, 'gaming-console,retro,linux,hybrid,atari'),
    ('Evercade VS', 'Home retro gaming console with HDMI output supporting Evercade cartridge library.', 99.99, 35, 11, 4.2, 'gaming-console,retro,cartridge,hdmi,evercade'),
    ('AYN Odin 2', 'Android gaming handheld with Snapdragon 8 Gen 2 and hall-effect analogue sticks.', 299.99, 30, 11, 4.6, 'handheld,android,gaming,snapdragon,hall-effect'),
    ('Playdate', 'Indie yellow handheld with hand crank, black-and-white reflective display and seasonal games.', 199.99, 40, 11, 4.4, 'handheld,indie,crank,monochrome,unique'),
    ('Nintendo Switch (OLED Model) White', 'Standard Nintendo Switch in white colorway with OLED screen and enhanced audio.', 349.99, 70, 11, 4.9, 'gaming-console,oled,portable,white,nintendo')
]