import os

# ── Database ──────────────────────────────────────────────────────────────────
DB_DIR: str = os.path.join(os.path.dirname(__file__), "data")
PRODUCTS_DB_PATH: str = os.path.join(DB_DIR, "products.db")
CART_DB_PATH: str = os.path.join(DB_DIR, "cart.db")

# ── Database data──────────────────────────────────────────────────────────────


SEED_CATEGORIES = [
    # (category_id, category_description)
    (
        "Mice & Pointing Devices",
        "Computer mice and pointing input devices, covering productivity-grade wireless mice, gaming mice with high-precision sensors, and platform-optimised options for Mac and PC users.",
    ),
    (
        "Keyboards",
        "Mechanical and wireless keyboards for gaming and productivity, including tenkeyless designs, customisable RGB lighting, dedicated macro keys, and low-profile switch options.",
    ),
    (
        "Monitors & Displays",
        "Gaming and professional monitors featuring high refresh rates, QHD and 4K resolutions, curved panels, and IPS/VA display technologies for immersive visual experiences.",
    ),
    (
        "Headphones & Audio",
        "Over-ear headphones, in-ear earbuds, and wireless audio devices with active noise cancellation, premium sound quality, adaptive transparency, and long battery life.",
    ),
    (
        "Cameras & Drones",
        "Mirrorless cameras with full-frame and APS-C sensors for professional photography and video, plus compact consumer drones with intelligent shooting modes and HDR video capability.",
    ),
    (
        "Wearables & Fitness",
        "Smartwatches and fitness trackers offering health monitoring, built-in GPS, heart rate tracking, stress management tools, and seamless integration with iOS and Android ecosystems.",
    ),
    (
        "Footwear",
        "Athletic running shoes, casual boots, and outdoor hiking footwear spanning cushioned road runners, waterproof hiking boots, iconic leather boots, and cosy winter sheepskin styles.",
    ),
    (
        "Clothing & Apparel",
        "Everyday clothing including denim jeans, casual trousers, cotton T-shirts, hoodies, and fleece outerwear from lifestyle and outdoor brands covering a range of fits and styles.",
    ),
    (
        "Home Appliances",
        "Kitchen and household appliances including cordless and robot vacuums, stand mixers, pressure cookers, blenders, smart refrigerators, washing machines, and multi-surface floor cleaners.",
    ),
    (
        "TVs & Home Entertainment",
        "Large-screen televisions featuring 4K HDR, QLED, and OLED display technologies with smart TV platforms, gaming modes, high contrast ratios, and vivid colour reproduction.",
    ),
    (
        "Gaming Consoles",
        "Next-generation and portable gaming consoles delivering high-performance 4K gaming, fast load times, immersive gameplay, and versatile play modes for home and on-the-go gaming.",
    ),
]


SEED_PRODUCTS = [
    # (name, description, price, stock, category_id, rating, tags)
    (
        "Logitech MX Master 3",
        "Ergonomic wireless mouse with precision tracking and customizable controls for productivity pros.",
        99.99,
        150,
        1,
        4.8,
        "wireless,ergonomic,productivity,office,precision,bluetooth,customisable",
    ),
    (
        "Razer DeathAdder V2",
        "High-precision gaming mouse with optical switches and ergonomic grip for competitive play.",
        69.99,
        120,
        1,
        4.7,
        "gaming,optical,ergonomic,competitive,high-precision",
    ),
    (
        "Apple Magic Mouse 2",
        "Multi-touch wireless mouse with rechargeable battery and sleek design for Mac ecosystems.",
        79.99,
        90,
        1,
        4.6,
        "wireless,multi-touch,mac,rechargeable,sleek",
    ),
    (
        "Corsair K95 RGB Platinum",
        "Premium mechanical keyboard with customizable RGB and dedicated macro keys for gamers.",
        199.99,
        60,
        2,
        4.7,
        "mechanical,RGB,gaming,macro,premium",
    ),
    (
        "Logitech G915 TKL",
        "Wireless mechanical keyboard with low-profile GL switches and LIGHTSYNC RGB lighting.",
        229.99,
        70,
        2,
        4.6,
        "wireless,mechanical,low-profile,RGB,gaming,tenkeyless",
    ),
    (
        "Razer BlackWidow V3",
        "Durable gaming keyboard with tactile switches and dynamic RGB lighting effects.",
        139.99,
        80,
        2,
        4.5,
        "gaming,mechanical,tactile,RGB,durable",
    ),
    (
        'Samsung Odyssey G7 27"',
        "Curved QHD monitor with 240Hz refresh and deep contrast for immersive gaming.",
        699.99,
        35,
        3,
        4.8,
        "curved,QHD,240Hz,gaming,immersive",
    ),
    (
        "LG UltraGear 27GL850",
        "QHD IPS gaming monitor with 144Hz refresh rate and rapid response time.",
        449.99,
        50,
        3,
        4.7,
        "QHD,IPS,144Hz,gaming,fast-response",
    ),
    (
        "Sony WH-1000XM4",
        "Industry-leading noise-cancelling headphones with premium audio clarity and comfort.",
        349.99,
        40,
        4,
        4.9,
        "noise-cancelling,wireless,premium,over-ear,bluetooth",
    ),
    (
        "Bose QuietComfort 45",
        "Comfortable wireless noise-cancelling headphones with up to 24-hour battery life.",
        329.99,
        45,
        4,
        4.8,
        "noise-cancelling,wireless,comfort,over-ear,24hr-battery",
    ),
    (
        "Apple AirPods Pro (2nd Gen)",
        "Wireless earbuds with active noise cancellation and adaptive transparency.",
        249.99,
        65,
        4,
        4.7,
        "wireless,earbuds,noise-cancelling,adaptive-transparency,apple",
    ),
    (
        "Beats Studio3 Wireless",
        "High-performance wireless headphones with pure adaptive noise-cancelling.",
        279.99,
        55,
        4,
        4.6,
        "wireless,noise-cancelling,over-ear,premium,adaptive",
    ),
    (
        "Google Pixel Buds Pro",
        "Wireless earbuds with premium sound and seamless Google Assistant integration.",
        199.99,
        70,
        4,
        4.5,
        "wireless,earbuds,google-assistant,premium-sound,android",
    ),
    (
        "Sony A7 III Mirrorless Camera",
        "Full-frame mirrorless camera with excellent low-light performance and advanced autofocus.",
        1999.99,
        20,
        5,
        4.8,
        "mirrorless,full-frame,low-light,autofocus,professional",
    ),
    (
        "Canon EOS R6",
        "Versatile mirrorless camera with fast continuous shooting and 4K video capture.",
        2499.99,
        15,
        5,
        4.7,
        "mirrorless,4K,continuous-shooting,professional,video",
    ),
    (
        "Nikon Z6 II",
        "Mirrorless camera offering excellent image quality and dual-processor performance.",
        1996.95,
        18,
        5,
        4.7,
        "mirrorless,dual-processor,image-quality,professional",
    ),
    (
        "DJI Mavic Air 2",
        "Compact drone with 4K HDR video and intelligent shooting modes.",
        799.99,
        30,
        5,
        4.8,
        "drone,4K,HDR,compact,intelligent-shooting",
    ),
    (
        "Fitbit Charge 5",
        "Advanced fitness tracker with built-in GPS, stress management, and heart rate monitoring.",
        149.95,
        120,
        6,
        4.4,
        "fitness-tracker,GPS,heart-rate,stress-management,health",
    ),
    (
        "Apple Watch Series 9",
        "Smartwatch with powerful performance, health tracking, and seamless iPhone integration.",
        399.99,
        80,
        6,
        4.8,
        "smartwatch,health-tracking,iphone,fitness,apple",
    ),
    (
        "Samsung Galaxy Watch 6",
        "Smartwatch with robust fitness features and long battery life.",
        349.99,
        75,
        6,
        4.6,
        "smartwatch,fitness,battery-life,android,samsung",
    ),
    (
        "Nike Air Zoom Pegasus 39",
        "Everyday running shoes with responsive cushioning and breathable mesh.",
        119.99,
        200,
        7,
        4.6,
        "running,cushioning,breathable,everyday,road",
    ),
    (
        "Adidas Ultraboost 22",
        "Boost technology for superior energy return and comfortable long runs.",
        179.99,
        180,
        7,
        4.7,
        "running,boost,energy-return,comfort,long-distance",
    ),
    (
        "New Balance Fresh Foam 1080v12",
        "Cushioned running shoes with plush Fresh Foam midsole for daily mileage.",
        149.99,
        160,
        7,
        4.5,
        "running,cushioned,daily-mileage,plush,fresh-foam",
    ),
    (
        "Saucony Kinvara 13",
        "Lightweight road running shoes with springy responsiveness.",
        129.99,
        140,
        7,
        4.5,
        "running,lightweight,responsive,road,springy",
    ),
    (
        "Timberland 6-Inch Premium Boot",
        "Rugged waterproof boots with padded collar for outdoor durability.",
        198.00,
        120,
        7,
        4.5,
        "boots,waterproof,rugged,outdoor,padded-collar",
    ),
    (
        "Dr. Martens 1460",
        "Classic leather boots with air-cushioned sole and iconic style.",
        150.00,
        90,
        7,
        4.6,
        "boots,leather,iconic,air-cushioned,classic",
    ),
    (
        "Columbia Newton Ridge Plus II",
        "Durable waterproof hiking boots with traction-ready outsole.",
        129.99,
        130,
        7,
        4.6,
        "hiking,waterproof,traction,outdoor,durable",
    ),
    (
        "UGG Classic Short II",
        "Comfortable sheepskin boots with cozy warmth for cold weather.",
        159.95,
        100,
        7,
        4.7,
        "boots,sheepskin,warm,winter,cozy",
    ),
    (
        "Levi's 501 Original Jeans",
        "Timeless straight-fit denim with button fly and authentic style.",
        59.99,
        250,
        8,
        4.4,
        "jeans,denim,straight-fit,classic,button-fly",
    ),
    (
        "Wrangler Authentics Slim Fit",
        "Comfortable slim-fit jeans with everyday style and durable build.",
        49.99,
        200,
        8,
        4.3,
        "jeans,slim-fit,everyday,durable,casual",
    ),
    (
        "Levi's 511 Slim Fit Jeans",
        "Modern slim cut denim with stretch for comfort and mobility.",
        69.99,
        210,
        8,
        4.5,
        "jeans,slim,stretch,modern,denim",
    ),
    (
        "Gap Classic Khaki Pants",
        "Versatile khaki pants with relaxed fit for everyday wear.",
        49.95,
        180,
        8,
        4.2,
        "pants,khaki,relaxed,everyday,versatile",
    ),
    (
        "Uniqlo Men Supima Cotton T-Shirt",
        "Soft Supima cotton tee with breathable comfort and classic design.",
        14.99,
        500,
        8,
        4.5,
        "t-shirt,supima-cotton,breathable,classic,soft",
    ),
    (
        "Hanes Men's Tagless Tee",
        "Tagless cotton t-shirt with comfort-first design for daily wear.",
        9.99,
        400,
        8,
        4.2,
        "t-shirt,cotton,tagless,daily,comfort",
    ),
    (
        "Champion Reverse Weave Hoodie",
        "Warm fleece hoodie with classic logo and durable construction.",
        59.99,
        150,
        8,
        4.6,
        "hoodie,fleece,logo,warm,durable",
    ),
    (
        "The North Face Denali Fleece Jacket",
        "Cozy fleece jacket with reinforced shoulders for outdoor warmth.",
        179.00,
        80,
        8,
        4.7,
        "jacket,fleece,outdoor,warm,reinforced",
    ),
    (
        "Patagonia Better Sweater",
        "Eco-friendly fleece sweater with full-zip comfort and rugged durability.",
        139.00,
        100,
        8,
        4.8,
        "sweater,fleece,eco-friendly,full-zip,outdoor",
    ),
    (
        "Dyson V15 Detect",
        "Cordless vacuum with laser dust detection and powerful suction for deep cleaning.",
        699.99,
        30,
        9,
        4.8,
        "vacuum,cordless,laser-detection,powerful,deep-clean",
    ),
    (
        "iRobot Roomba i7+",
        "Smart robot vacuum with automatic dirt disposal and smart mapping.",
        799.99,
        25,
        9,
        4.7,
        "robot-vacuum,smart-mapping,auto-disposal,wifi,smart",
    ),
    (
        "Ninja Foodi Blender",
        "High-speed blender with precision blades for smooth blending and crushing ice.",
        129.99,
        60,
        9,
        4.6,
        "blender,high-speed,ice-crushing,kitchen,smoothie",
    ),
    (
        "KitchenAid Artisan Mixer",
        "Iconic stand mixer with 10 speeds and versatile attachments for baking.",
        379.99,
        40,
        9,
        4.9,
        "stand-mixer,baking,10-speed,attachments,kitchen",
    ),
    (
        "Instant Pot Duo 7-in-1",
        "Multi-use pressure cooker with customizable programs and reliable performance.",
        99.95,
        70,
        9,
        4.7,
        "pressure-cooker,multi-use,programmable,kitchen,rice-cooker",
    ),
    (
        "Samsung Family Hub Refrigerator",
        "Smart refrigerator with touchscreen display and flexible storage options.",
        2499.99,
        10,
        9,
        4.6,
        "refrigerator,smart,touchscreen,storage,connected",
    ),
    (
        "LG ThinQ Washer",
        "Smart washer with AI fabric care and energy-efficient performance.",
        899.99,
        15,
        9,
        4.5,
        "washer,smart,AI-fabric-care,energy-efficient,laundry",
    ),
    (
        'Sony X900H 65" TV',
        "4K HDR Smart LED TV with immersive picture quality and gaming mode.",
        1299.99,
        20,
        10,
        4.7,
        "4K,HDR,smart-TV,LED,gaming-mode,65-inch",
    ),
    (
        'Samsung Q80T 55" QLED',
        "Vibrant QLED display with impressive contrast and motion handling.",
        1099.99,
        18,
        10,
        4.6,
        "QLED,4K,contrast,motion-handling,55-inch",
    ),
    (
        'LG CX 65" OLED',
        "Stunning OLED picture with deep blacks and rich colors.",
        2499.99,
        12,
        10,
        4.8,
        "OLED,4K,deep-blacks,rich-colors,65-inch,premium",
    ),
    (
        "Bissell CrossWave Floor Cleaner",
        "All-in-one wet and dry floor cleaner with multi-surface cleaning.",
        299.99,
        30,
        9,
        4.5,
        "floor-cleaner,wet-dry,multi-surface,all-in-one,vacuum",
    ),
    (
        "Miele Classic C1 Vacuum",
        "Reliable canister vacuum with powerful suction and quiet operation.",
        399.99,
        25,
        9,
        4.7,
        "vacuum,canister,powerful,quiet,reliable",
    ),
    (
        "Sony PlayStation 5",
        "Next-gen gaming console with lightning-fast load times and immersive gaming.",
        499.99,
        50,
        11,
        4.9,
        "gaming-console,next-gen,fast-loading,immersive,4K",
    ),
    (
        "Microsoft Xbox Series X",
        "Powerful gaming console with 4K gaming and high performance.",
        499.99,
        45,
        11,
        4.8,
        "gaming-console,4K,high-performance,xbox,next-gen",
    ),
    (
        "Nintendo Switch OLED",
        "Versatile gaming system with vibrant OLED screen and portable play.",
        349.99,
        60,
        11,
        4.9,
        "gaming-console,portable,OLED,versatile,handheld",
    ),
]
